builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -buildid= -w -s -X github-integrations/main.Version={{ .Env.RELEASE_VERSION }}
    flags:
      - -trimpath
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'
      - '6'
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

changelog:
  skip: true

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_v{{ .Env.RELEASE_VERSION }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}"'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Env.RELEASE_VERSION }}_checksums.txt"
