dist: trusty
language: java
jdk:
  - openjdk8
  
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar
   
addons:
  sonarcloud:
    organization: "dadrus-github"

install: true

script:
  - build.sh

