dist: trusty
language: java
jdk:
  - openjdk8
  
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar
   
addons:
  sonarcloud:
    organization: "dadrus-github"
    github_token:
      secure: "u1bazNsWVAu89Unm7NDq9tpHXQ8VHKkmOMoN9dA03CMHzrOJsFrMI6qbvBXjbXaT8qZ7E8jni0oPMOLXZY/q7QCG+EA/TMGp6/FaWLQ8flEQlB+fulaatpGMGjskXLJCQ1fv7/9e8tnQcXDu8nAPSOc8oF6038rqWbJx9FheayrxoJU0anI52aMUmmOHKXLl58xnu74xNy4yWYBD7WK3Jm2cwsmji4VsGqvff8HacsuU5DWpsQ1RGVfwKzCsj9YC2jpq8SG8X453Jd0xcBNApu18/I/h8dyj0I6yfmchG9xKC2DKE/J+US/Qn1z0hPTHJ668/lZSDjk8b8yRLt9hZXCZTX0yQLIpWRvtitQulcCd8FfK5tKfhP5ZdzAv/Jdjg6UP36bFvn0dteI7MKtQfp5uSYc+1Q8Mn5aRyjEbwINsNhO+YhX1ddDw7HsVZd4GZjOAQgdfaSZmwKBdWpKA6iJMMcHr9q877Rw6t2oxfQrPmGq8YQbYJGP4mxMq3G0PfspXampssenFG2ea60z5F28JC6QMrBmUkBaEVEwbA7CEmVkKe10OWeWtq0Q+MYXhbk2fjEChqbC6YPR9jTnDy7k2CjUdEtkmHZhK9nTTonqoSoNpKBS3aFfDN0mKSDNuec4RdSD/q+jbRo/916tBCpn0UjroM4pQ4r9V002x3e8=""qDHusfzttz2H7ZYvWRuT9pa/D24VF8A69p6pzFZuXe+ufbT50rM1O9zrOInPU738d53YOPb0BRgdUPzDzBNg/ycoEhr+3N0gVf76dFhGPp3bkUn+nRPtVVH2IIL9Clo4nB8y70ka8rLexb587d0NOsmI0hsQriAUpfOOSzFQFl8yJMJaZZmUc9hu8JbrMdtisXNUTBznFFW8O1n8VpzF0iHBOJLsSeGRM9uisfN7W3EtRjAOp/2u27SI2UF93rZd3e7sB2BYXRkzCtM3d0Xi66nhQ1BUzbFVuovk8dbknSo8oeW2awPZw1aGFncNNL3ZqCVFHtUDBuak4AHDO403a/6SymqSOpqV7Y9itck2zn31XU30hmPzmatJ+OyDfw4C9466Uel8UaiuHwVzkXeK0YOspd4kxMIzjxngLMC9OT92HSMTw7HwNdR994R9aiHsY7ZSMdw784HNwgTczIbKLvgYq/rX168mx5wGMTAyoMuVOwNgXX10AiZ7KSBBIFqlESJjHtv64tvijA4kceINCGFmGXgSziazpIC8OqNJdOMH0HYX/2IvIyJb5FVbU9mrfQn5e6ySjeM2ZV3HNlYaUgi3pGVuaynuJcsFozBkQAOgyJhWVeW06nTqJvhZTEMwxrmfThnqCI9EuRz+7cnRYNfaTWJwID5wJNjGZkR8U9s="
   

install: true

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - mvn clean verify sonar:sonar

