apiVersion: v1
entries:
  github-integrations:
  - apiVersion: v2
    appVersion: 0.56.0-alpha
    created: "2025-03-26T11:43:30.766520502Z"
    description: GH Integration tests
    digest: 3b89114990e713e5e1dd42d451e9ecfec8d8bce04baebf852b1f25ce3a0e18e0
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.13.0.tgz
    version: 0.13.0
  - apiVersion: v2
    appVersion: 0.55.3-alpha
    created: "2025-03-26T09:11:33.125804073Z"
    description: GH Integration tests
    digest: 559def879bfd1499fe70667514e30767f118d37298e526ee6d901aae9a83efe9
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.12.0.tgz
    version: 0.12.0
  - apiVersion: v2
    appVersion: 0.54.0-alpha
    created: "2025-03-25T17:04:09.260009622Z"
    description: GH Integration tests
    digest: c20e80330da83935a1bde343d18e0b83cc81b69dbd6ca7967240b703b1f9155e
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.11.0.tgz
    version: 0.11.0
  - apiVersion: v2
    appVersion: 0.53.0-alpha
    created: "2025-03-25T14:45:19.453255691Z"
    description: GH Integration tests
    digest: fe53ff01d28dae335e0aab8e87fca1c51d052c5d0fe030fcb0762b7ffe588d53
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.10.0.tgz
    version: 0.10.0
  - apiVersion: v2
    appVersion: 0.52.14-alpha
    created: "2025-03-25T14:37:26.749563586Z"
    description: GH Integration tests
    digest: 7a45b5474ad9eebb2a82daed98e77b296b9ec152207f5b2797d7442ba7377a61
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.9.2.tgz
    version: 0.9.2
  - apiVersion: v2
    appVersion: 0.52.13-alpha
    created: "2025-03-25T14:24:09.305242966Z"
    description: GH Integration tests
    digest: ab0f73c4842a4244be54bbed9f7dcb03a760086a293bfa80fbb2045d3c930d29
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.9.1.tgz
    version: 0.9.1
  - apiVersion: v2
    appVersion: 0.52.12-alpha
    created: "2025-03-25T14:00:23.613181849Z"
    description: GH Integration tests
    digest: 04cea5445a4906325ee1310211dbe949d07a58492fd4dfc417fb32fdd0861807
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.9.0.tgz
    version: 0.9.0
  - apiVersion: v2
    appVersion: 0.52.9-alpha
    created: "2025-03-25T13:12:27.738088424Z"
    description: GH Integration tests
    digest: b80c53d8479b1c6e29b0390f816e1702d514761bab64e4fc936f119fab1f2955
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: github-integrations
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/github-integrations-0.8.2.tgz
    version: 0.8.2
  heimdall:
  - apiVersion: v2
    appVersion: 0.52.7-alpha
    created: "2025-03-25T12:49:44.398818585Z"
    description: A cloud native Identity Aware Proxy and Access Control Decision Service
    digest: a01ab37455beb4add9a75f22e98acb67ddc6f3298a75c3d49b073154ef13cc86
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: heimdall
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/heimdall-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: 0.4.1-alpha
    created: "2023-06-29T00:55:18.895567061Z"
    description: A cloud native Identity Aware Proxy and Access Control Decision API
    digest: 39e536ccc31c78eedfc317eb4b568026646868276f93d7a283e9b74d3f0f48c0
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: heimdall
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/heimdall-0.1.0.tgz
    version: 0.1.0
generated: "2025-03-26T11:43:30.765528905Z"
