apiVersion: v1
entries:
  heimdall:
  - apiVersion: v2
    appVersion: 0.34.0-alpha
    created: "2023-07-27T16:20:33.56125724Z"
    description: A cloud native Identity Aware Proxy and Access Control Decision Service
    digest: 2852ebc7531c6327362cb38775e14bfae9c9c937dec28c7d2eb70e6a9da67786
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    kubeVersion: ^1.19.0
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: heimdall
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/heimdall-0.8.2.tgz
    version: 0.8.2
  - apiVersion: v2
    appVersion: 0.4.1-alpha
    created: "2023-06-29T00:55:18.895567061Z"
    description: A cloud native Identity Aware Proxy and Access Control Decision API
    digest: 39e536ccc31c78eedfc317eb4b568026646868276f93d7a283e9b74d3f0f48c0
    home: https://dadrus.github.io/heimdall/
    keywords:
    - zero-trust
    - authentication
    - authorization
    - access-control
    - access-management
    - policy-enforcement
    - oauth2
    - openid-connect
    - iap
    - auth-proxy
    - identity-aware-proxy
    - decision-api
    - auth-filter
    maintainers:
    - email: dadrus@gmx.de
      name: Dimitrij Drus
    name: heimdall
    sources:
    - https://github.com/dadrus/heimdall
    type: application
    urls:
    - https://dadrus.github.io/github-integrations/charts/heimdall-0.1.0.tgz
    version: 0.1.0
generated: "2023-07-27T16:20:33.558879885Z"
