name: Build and publish docs
description: Builds and publishes project documentation

inputs:
  publish_dir:
    description: The destination subdirectory on a publishing branch. Defaults to dev
    required: false
    default: dev
  docs_dir:
    description: The directory containing the documentation. Defaults to docs
    required: false
    default: docs
  github_token:
    description: The github token to use for publishing
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3
      with:
        hugo-version: 0.100.1
        extended: true
    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: 17.7
    - name: Install mermaid
      shell: bash
      run: npm install -g @mermaid-js/mermaid-cli
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install asciidoctor
      shell: bash
      run: gem install asciidoctor asciidoctor-diagram asciidoctor-html5s rouge
    - name: Install dependencies
      working-directory: ${{ inputs.docs_dir }}
      shell: bash
      run: npm install
    - name: Build documentation
      working-directory: ${{ inputs.docs_dir }}
      shell: bash
      run: hugo --minify -d ./public
    - name: Deploy documentation
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4
      with:
        github_token: ${{ inputs.github_token }}
        publish_dir: ${{ inputs.docs_dir }}/public
        destination_dir: ${{ inputs.publish_dir }}