baseURL: https://dadrus.github.io/
languageCode: en-us
title: Test
theme: mytheme
relativeURLS: true
sectionPagesMenu: main
enableGitInfo: true

security:
  enableInlineShortcodes: false
  exec:
    allow: ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', 'asciidoctor']
    osEnv: ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  funcs:
    getenv: ['^HUGO_']

  http:
    methods: ['(?i)GET|POST']
    urls: ['.*']

markup:
  asciidocExt:
    extensions: ['asciidoctor-diagram', 'asciidoctor-html5s']
    backend: html5
    trace: true
    verbose: true
    workingFolderCurrent: true
    attributes:
      source-highlighter: rouge
      rouge-css: style
      rouge-style: monokai.sublime
      icons: font


menu:
  main:
    - identifier: docs
      title: Docs
      url: docs/welcome
      weight: 100
    - identifier: api
      title: API
      url: docs/api/
      weight: 200
    - identifier: get_started
      title: Getting Started
      weight: 300

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - ':fileModTime'
    - ':default'

params:
  author: Dimitrij Drus
  description: Test docu
  github:
    user: dadrus
    project: github-integrations

module:
  mounts:
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.js
      target: assets/js/bootstrap.bundle.js