name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test_and_build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test
      run: go test -v ./...
    - name: Build
      run: GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-buildid= -w -s -X main.Version=${{ github.sha }}"
    - uses: actions/upload-artifact@v3
      with:
        name: build-result
        path: github-integrations


  build-docker-mages:
    runs-on: ubuntu-20.04
    needs:
     - test_and_build
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Docker meta
       id: meta
       uses: docker/metadata-action@v4
       with:
         images: ${{ secrets.DOCKERHUB_USER }}/test:latest
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
         context: .
         file: ./docker/Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm
         push: false
         tags: ${{ secrets.DOCKERHUB_USER }}/test:latest
