name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.4
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test
        run: go test -v ./...

  prepare-release:
    runs-on: ubuntu-20.04
    if: github.ref == 'refs/heads/main'
    needs:
      - test
    outputs:
      release_created: ${{ steps.release_prepare.outputs.release_created }}
      tag_name: ${{ steps.release_prepare.outputs.tag_name }}
    steps:
      - name: Prepare Release
        id: release_prepare
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: release-bot[bot] <${{ github.run_id }}+release-bot[bot]@users.noreply.github.com>

  build:
    runs-on: ubuntu-20.04
    needs:
      - test
      - prepare-release
    if: |
      always() && 
      needs.prepare-release.outputs.release_created == false &&
      needs.test.result == 'success'
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64, arm ]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.4
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Build
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -ldflags="-buildid= -w -s -X main.Version=${{ github.sha }}" -o ./build/
    - uses: actions/upload-artifact@v3
      if: success()
      with:
        name: build-result-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./build/*
        retention-days: 30

  # This job is executed only if the prepare-release job has created a release
  release-binaries:
    runs-on: ubuntu-20.04
    needs:
      - prepare-release
    if: needs.prepare-release.outputs.release_created
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64, arm ]
        exclude:
          - goarch: arm
            goos: darwin
          - goarch: arm
            goos: windows
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          release_tag: ${{ needs.prepare-release.outputs.tag_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.18.4
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-buildid= -w -s -X main.Version=${{ needs.prepare-release.outputs.tag_name }}"
          build_flags: -trimpath
          sha256sum: true
          md5sum: false
          extra_files: CHANGELOG.md README.md

  # this job is here only for the verification purpose of the docker images build
  build-docker-images:
    runs-on: ubuntu-20.04
    needs:
     - test
     - prepare-release
    if: |
      always() && 
      needs.prepare-release.outputs.release_created == false &&
      needs.test.result == 'success'
    steps:
     - name: Checkout repository
       uses: actions/checkout@v3
     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and push
       uses: docker/build-push-action@v3
       with:
         context: .
         file: ./docker/Dockerfile
         platforms: linux/amd64,linux/arm64,linux/arm
         push: false
         build-args: VERSION=${{ github.sha }}
         tags: ${{ github.repository }}:latest

  # This job is executed only if the prepare-release job has created a release
  release-docker-images:
    runs-on: ubuntu-20.04
    needs:
      - prepare-release
    if: needs.prepare-release.outputs.release_created
    steps:
      - name: Prepare image version
        id: image-version
        run: |
          export version=$(echo ${{ needs.prepare-release.outputs.tag_name }} |  sed 's/v//g')
          echo ::set-output name=result::$version
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ github.repository }}
          labels: |
            org.opencontainers.image.version=${{ steps.image-version.outputs.result }}
            org.opencontainers.image.documentation=https://dadrus.github.io/heimdall/
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm
          push: true
          build-args: VERSION=${{ needs.prepare-release.outputs.tag_name }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ github.repository }}:${{ steps.image-version.outputs.result }},${{ github.repository }}:latest
      - name: Update DockerHub repository description & readme
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
          readme-filepath: ./README.md

  build-and-publish-docs:
    runs-on: ubuntu-20.04
    needs:
      - prepare-release
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 0.100.1
          extended: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 17.7
      - name: Install mermaid
        run: npm install -g @mermaid-js/mermaid-cli
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install asciidoctor
        run: gem install asciidoctor asciidoctor-diagram asciidoctor-html5s rouge
      - name: Install dependencies
        working-directory: ./docs
        run: npm install
      - name: Update version string to new released version
        if: needs.prepare-release.outputs.release_created
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "x-current-version"
          replace: "${{ needs.prepare-release.outputs.tag_name }}"
          regex: false
          include: docs/**
      - name: Update version string to dev version
        if: github.ref == 'refs/heads/main' && needs.prepare-release.outputs.release_created == false
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "x-current-version"
          replace: "dev"
          regex: false
          include: docs/**
      - name: Build documentation
        working-directory: ./docs
        run: hugo --minify -d ./public
      - name: Update uri for redirecting to new version
        if: needs.prepare-release.outputs.release_created
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "x-released-version"
          replace: "${{ needs.prepare-release.outputs.tag_name }}"
          regex: false
          include: docs/**
      - name: Update versions.json
        id: update-version-json
        if: needs.prepare-release.outputs.release_created
        run: |
          cat ./docs/versions/data.json | jq '. + [{ "version": "${{ needs.prepare-release.outputs.tag_name }}", "path": "/heimdall/${{ needs.prepare-release.outputs.tag_name }}/docs/welcome/" }]' | tee ./docs/versions/data.json
      - name: Deploy dev documentation
        if: github.ref == 'refs/heads/main' && needs.prepare-release.outputs.release_created == false
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          destination_dir: dev
      - name: Deploy released documentation
        if: needs.prepare-release.outputs.release_created
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/public
          destination_dir: ${{ needs.prepare-release.outputs.tag_name }}
      - name: Deploy redirect to new released version
        uses: peaceiris/actions-gh-pages@v3
        if: needs.prepare-release.outputs.release_created
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/redirect
          keep_files: true
      - name: Deploy versions JSON document
        uses: peaceiris/actions-gh-pages@v3
        if: needs.prepare-release.outputs.release_created
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/versions
          keep_files: true
      - name: Commit updated versions JSON document
        if: steps.update-version-json.outcome == 'success' && needs.prepare-release.outputs.release_created
        run: |
          git config --local user.email "{{ github.sha }}+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ./docs/versions/data.json
          git commit -m "chore: Preparing for next iteration"
      - name: Push changes
        if: needs.prepare-release.outputs.release_created
        uses: ad-m/github-push-action@master
