name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test_and_build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test
      run: go test -v ./...
    - name: Prepare Release
      id: release_prepare
      uses: google-github-actions/release-please-action@v3
      with:
        command: manifest
    - name: Release Build
      if: ${{ steps.release_prepare.outputs.release_created }}
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-buildid= -w -s -X main.Version=${{ steps.release_prepare.outputs.tag_name }}"
    - name: Build
      if: not ${{ steps.release_prepare.outputs.release_created }}
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-buildid= -w -s -X main.Version=${{ github.sha }}"
    - uses: actions/upload-artifact@v3
      with:
        name: build-result
        path: github-integrations


