name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  test_and_build:
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test
      run: go test -v ./...
    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -ldflags="-buildid= -w -s -X main.Version=${{ github.ref }}"
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: github-integrations
    - name: Prepare Release
      id: release_prepare
      uses: google-github-actions/release-please-action@v3
      with:
        command: manifest
    - name: Upload Assets to Release
      uses: AButler/upload-release-assets@v2.0
      if: ${{ steps.release_prepare.outputs.release_created }}
      with:
        release-tag: ${{ steps.release_prepare.outputs.tag_name }}
        files: github-integrations

