name: Release Binaries

on:
  release:
    types: [published]

jobs:
  release-binaries:
    name: Release Go Binary
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/amd64, linux/arm64, windows/amd64, darwin/amd64, darwin/arm64
        goos: [ linux, windows, darwin ]
        goarch: [ amd64, arm64 ]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: "-buildid= -w -s -X main.Version=${{ github.ref_name }}"
          build_flags: -trimpath
          extra_files: CHANGELOG.md README.md